/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_victorcruz;

/**
 *
 * @author Victor Jafet Cruz
 */
public class Lab6P2_VictorCruz extends javax.swing.JFrame {

    /**
     * Creates new form Lab6P2_VictorCruz
     */
    public Lab6P2_VictorCruz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_MenuAdmin = new javax.swing.JDialog();
        jToolBar3 = new javax.swing.JToolBar();
        JB_SalirCuentaAdmin = new javax.swing.JButton();
        JB_SalirSistemaAdmin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_CRUDMaestros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMI_CRUDClases = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMI_CRUDAlumnos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMI_CRUDProyectos = new javax.swing.JMenuItem();
        JD_MenuMaestro = new javax.swing.JDialog();
        jToolBar2 = new javax.swing.JToolBar();
        JB_SalirCuentaMaestro = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        JMI_ProyectosMaestro = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        JMI_VerClasesAsignadas = new javax.swing.JMenuItem();
        JD_MenuAlumno = new javax.swing.JDialog();
        jToolBar1 = new javax.swing.JToolBar();
        JB_SalirCuentaAlumno = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        JMI_Matricula = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        JMI_VerInfoClaseProyecto = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        JMI_ListarModificarAlumnos = new javax.swing.JMenuItem();
        JD_AdministracionMaestros = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JD_AdministracionAlumnos = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JD_AdministracionClases = new javax.swing.JDialog();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JD_AdminstracionProyectos = new javax.swing.JDialog();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JD_CrudMaestroProyecto = new javax.swing.JDialog();
        JD_ClasesAsignadasMaestros = new javax.swing.JDialog();
        JD_MatriculaAlumnos = new javax.swing.JDialog();
        JD_VerInfoProyectos = new javax.swing.JDialog();
        JD_ListarModficarAlumnos = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_Username = new javax.swing.JTextField();
        PF_Password = new javax.swing.JPasswordField();
        JB_Login = new javax.swing.JButton();
        JB_SalirSistema = new javax.swing.JButton();

        jToolBar3.setRollover(true);

        JB_SalirCuentaAdmin.setText("Salir Cuenta");
        JB_SalirCuentaAdmin.setFocusable(false);
        JB_SalirCuentaAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirCuentaAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(JB_SalirCuentaAdmin);

        JB_SalirSistemaAdmin.setText("Salir sistema");
        JB_SalirSistemaAdmin.setFocusable(false);
        JB_SalirSistemaAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirSistemaAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(JB_SalirSistemaAdmin);

        jMenu1.setText("Adminstracion Maestros");

        JMI_CRUDMaestros.setText("CRUD Maestros");
        JMI_CRUDMaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDMaestrosActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CRUDMaestros);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Adminstracion de Clases");

        JMI_CRUDClases.setText("CRUD Clases");
        JMI_CRUDClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDClasesActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_CRUDClases);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Adminstracion de Alumnos");

        JMI_CRUDAlumnos.setText("CRUD Alumnos");
        JMI_CRUDAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDAlumnosActionPerformed(evt);
            }
        });
        jMenu3.add(JMI_CRUDAlumnos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Administracion de Proyectos");

        JMI_CRUDProyectos.setText("CRUD Proyectos");
        JMI_CRUDProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDProyectosActionPerformed(evt);
            }
        });
        jMenu4.add(JMI_CRUDProyectos);

        jMenuBar1.add(jMenu4);

        JD_MenuAdmin.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout JD_MenuAdminLayout = new javax.swing.GroupLayout(JD_MenuAdmin.getContentPane());
        JD_MenuAdmin.getContentPane().setLayout(JD_MenuAdminLayout);
        JD_MenuAdminLayout.setHorizontalGroup(
            JD_MenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuAdminLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 619, Short.MAX_VALUE))
        );
        JD_MenuAdminLayout.setVerticalGroup(
            JD_MenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuAdminLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 456, Short.MAX_VALUE))
        );

        jToolBar2.setRollover(true);

        JB_SalirCuentaMaestro.setText("Salir Cuenta");
        JB_SalirCuentaMaestro.setFocusable(false);
        JB_SalirCuentaMaestro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirCuentaMaestro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_SalirCuentaMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirCuentaMaestroMouseClicked(evt);
            }
        });
        jToolBar2.add(JB_SalirCuentaMaestro);

        jMenu5.setText("Administrar Proyectos");

        JMI_ProyectosMaestro.setText("CRUD Proyectos");
        JMI_ProyectosMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ProyectosMaestroActionPerformed(evt);
            }
        });
        jMenu5.add(JMI_ProyectosMaestro);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Ver Clases Asignadas");

        JMI_VerClasesAsignadas.setText("Ver Tabla de Clases");
        JMI_VerClasesAsignadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_VerClasesAsignadasActionPerformed(evt);
            }
        });
        jMenu6.add(JMI_VerClasesAsignadas);

        jMenuBar2.add(jMenu6);

        JD_MenuMaestro.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout JD_MenuMaestroLayout = new javax.swing.GroupLayout(JD_MenuMaestro.getContentPane());
        JD_MenuMaestro.getContentPane().setLayout(JD_MenuMaestroLayout);
        JD_MenuMaestroLayout.setHorizontalGroup(
            JD_MenuMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        JD_MenuMaestroLayout.setVerticalGroup(
            JD_MenuMaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuMaestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        JB_SalirCuentaAlumno.setText("Salir Cuenta");
        JB_SalirCuentaAlumno.setFocusable(false);
        JB_SalirCuentaAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirCuentaAlumno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_SalirCuentaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirCuentaAlumnoMouseClicked(evt);
            }
        });
        jToolBar1.add(JB_SalirCuentaAlumno);

        jMenu7.setText("Matricula");

        JMI_Matricula.setText("Matricular a un Clase");
        JMI_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_MatriculaActionPerformed(evt);
            }
        });
        jMenu7.add(JMI_Matricula);

        jMenuBar3.add(jMenu7);

        jMenu8.setText("Ver Info de Clase y Proyectos");

        JMI_VerInfoClaseProyecto.setText("Ver Info ");
        JMI_VerInfoClaseProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_VerInfoClaseProyectoActionPerformed(evt);
            }
        });
        jMenu8.add(JMI_VerInfoClaseProyecto);

        jMenuBar3.add(jMenu8);

        jMenu9.setText("Listar y Modificar Alumnos");

        JMI_ListarModificarAlumnos.setText("Listar/Modficar");
        JMI_ListarModificarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_ListarModificarAlumnosActionPerformed(evt);
            }
        });
        jMenu9.add(JMI_ListarModificarAlumnos);

        jMenuBar3.add(jMenu9);

        JD_MenuAlumno.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout JD_MenuAlumnoLayout = new javax.swing.GroupLayout(JD_MenuAlumno.getContentPane());
        JD_MenuAlumno.getContentPane().setLayout(JD_MenuAlumnoLayout);
        JD_MenuAlumnoLayout.setHorizontalGroup(
            JD_MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuAlumnoLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 542, Short.MAX_VALUE))
        );
        JD_MenuAlumnoLayout.setVerticalGroup(
            JD_MenuAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuAlumnoLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modficar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ELiminar", jPanel4);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Administracion de Maestros");

        javax.swing.GroupLayout JD_AdministracionMaestrosLayout = new javax.swing.GroupLayout(JD_AdministracionMaestros.getContentPane());
        JD_AdministracionMaestros.getContentPane().setLayout(JD_AdministracionMaestrosLayout);
        JD_AdministracionMaestrosLayout.setHorizontalGroup(
            JD_AdministracionMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdministracionMaestrosLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(JD_AdministracionMaestrosLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_AdministracionMaestrosLayout.setVerticalGroup(
            JD_AdministracionMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdministracionMaestrosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Agregar", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Modficar", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Listar", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("ELiminar", jPanel8);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Administracion de Alumnos");

        javax.swing.GroupLayout JD_AdministracionAlumnosLayout = new javax.swing.GroupLayout(JD_AdministracionAlumnos.getContentPane());
        JD_AdministracionAlumnos.getContentPane().setLayout(JD_AdministracionAlumnosLayout);
        JD_AdministracionAlumnosLayout.setHorizontalGroup(
            JD_AdministracionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdministracionAlumnosLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdministracionAlumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JD_AdministracionAlumnosLayout.setVerticalGroup(
            JD_AdministracionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdministracionAlumnosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Agregar", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Modficar", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Listar", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("ELiminar", jPanel12);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Administracion de Clases");

        javax.swing.GroupLayout JD_AdministracionClasesLayout = new javax.swing.GroupLayout(JD_AdministracionClases.getContentPane());
        JD_AdministracionClases.getContentPane().setLayout(JD_AdministracionClasesLayout);
        JD_AdministracionClasesLayout.setHorizontalGroup(
            JD_AdministracionClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdministracionClasesLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdministracionClasesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JD_AdministracionClasesLayout.setVerticalGroup(
            JD_AdministracionClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdministracionClasesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Agregar", jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Modficar", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Listar", jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("ELiminar", jPanel16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Administracion de Proyectos");

        javax.swing.GroupLayout JD_AdminstracionProyectosLayout = new javax.swing.GroupLayout(JD_AdminstracionProyectos.getContentPane());
        JD_AdminstracionProyectos.getContentPane().setLayout(JD_AdminstracionProyectosLayout);
        JD_AdminstracionProyectosLayout.setHorizontalGroup(
            JD_AdminstracionProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdminstracionProyectosLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdminstracionProyectosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JD_AdminstracionProyectosLayout.setVerticalGroup(
            JD_AdminstracionProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdminstracionProyectosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout JD_CrudMaestroProyectoLayout = new javax.swing.GroupLayout(JD_CrudMaestroProyecto.getContentPane());
        JD_CrudMaestroProyecto.getContentPane().setLayout(JD_CrudMaestroProyectoLayout);
        JD_CrudMaestroProyectoLayout.setHorizontalGroup(
            JD_CrudMaestroProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_CrudMaestroProyectoLayout.setVerticalGroup(
            JD_CrudMaestroProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_ClasesAsignadasMaestrosLayout = new javax.swing.GroupLayout(JD_ClasesAsignadasMaestros.getContentPane());
        JD_ClasesAsignadasMaestros.getContentPane().setLayout(JD_ClasesAsignadasMaestrosLayout);
        JD_ClasesAsignadasMaestrosLayout.setHorizontalGroup(
            JD_ClasesAsignadasMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_ClasesAsignadasMaestrosLayout.setVerticalGroup(
            JD_ClasesAsignadasMaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_MatriculaAlumnosLayout = new javax.swing.GroupLayout(JD_MatriculaAlumnos.getContentPane());
        JD_MatriculaAlumnos.getContentPane().setLayout(JD_MatriculaAlumnosLayout);
        JD_MatriculaAlumnosLayout.setHorizontalGroup(
            JD_MatriculaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_MatriculaAlumnosLayout.setVerticalGroup(
            JD_MatriculaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_VerInfoProyectosLayout = new javax.swing.GroupLayout(JD_VerInfoProyectos.getContentPane());
        JD_VerInfoProyectos.getContentPane().setLayout(JD_VerInfoProyectosLayout);
        JD_VerInfoProyectosLayout.setHorizontalGroup(
            JD_VerInfoProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_VerInfoProyectosLayout.setVerticalGroup(
            JD_VerInfoProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_ListarModficarAlumnosLayout = new javax.swing.GroupLayout(JD_ListarModficarAlumnos.getContentPane());
        JD_ListarModficarAlumnos.getContentPane().setLayout(JD_ListarModficarAlumnosLayout);
        JD_ListarModficarAlumnosLayout.setHorizontalGroup(
            JD_ListarModficarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_ListarModficarAlumnosLayout.setVerticalGroup(
            JD_ListarModficarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Login ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Username: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Password: ");

        JB_Login.setText("Login");
        JB_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_LoginMouseClicked(evt);
            }
        });

        JB_SalirSistema.setText("Salir del sistema");
        JB_SalirSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirSistemaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TF_Username)
                                    .addComponent(PF_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(JB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(JB_SalirSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TF_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(PF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_SalirSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_LoginMouseClicked
        // TODO add your handling code here:
        if(TF_Username.getText().equalsIgnoreCase("admin")&&PF_Password.getText().equalsIgnoreCase("1234")){
            Admin();
        }else{
            Administra_Clientes ap=
            new Administra_Clientes("./Clientes.txt");
            ap.cargarArchivo();
            //System.out.println(ap);
            int check=0;
            for (int i = 0; i < ap.getListaClientes().size(); i++) {
                if(ap.getListaClientes().get(i).getUsername().equalsIgnoreCase(TF_Username.getText())&&ap.getListaClientes().get(i).getClave().equalsIgnoreCase(PF_Password.getText())){
                    check=1;
                    numero=i;
                }
            }
            if(check==1){
                Clientes();
            }else{
                JOptionPane.showMessageDialog(this, "Su cuenta no existe porfavor registrela");
            }
        }
    }//GEN-LAST:event_JB_LoginMouseClicked

    private void JB_SalirSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirSistemaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JB_SalirSistemaMouseClicked

    private void JMI_CRUDMaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDMaestrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_CRUDMaestrosActionPerformed

    private void JMI_CRUDClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDClasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_CRUDClasesActionPerformed

    private void JMI_CRUDAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_CRUDAlumnosActionPerformed

    private void JMI_CRUDProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDProyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_CRUDProyectosActionPerformed

    private void JMI_ProyectosMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ProyectosMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_ProyectosMaestroActionPerformed

    private void JMI_VerClasesAsignadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_VerClasesAsignadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_VerClasesAsignadasActionPerformed

    private void JMI_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_MatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_MatriculaActionPerformed

    private void JMI_VerInfoClaseProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_VerInfoClaseProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_VerInfoClaseProyectoActionPerformed

    private void JMI_ListarModificarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_ListarModificarAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_ListarModificarAlumnosActionPerformed

    private void JB_SalirCuentaMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirCuentaMaestroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_SalirCuentaMaestroMouseClicked

    private void JB_SalirCuentaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirCuentaAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_SalirCuentaAlumnoMouseClicked

    
    public void AdminMaestros() {
        JD_AdministracionMaestros.pack();
        JD_AdministracionMaestros.setModal(true);
        JD_AdministracionMaestros.setLocationRelativeTo(this);
        JD_AdministracionMaestros.setVisible(true);
    }//fin del llamado del JDialog
    
    public void AdminClases() {
        JD_AdministracionClases.pack();
        JD_AdministracionClases.setModal(true);
        JD_AdministracionClases.setLocationRelativeTo(this);
        JD_AdministracionClases.setVisible(true);
    }//fin del llamado del JDialog
    
    public void AdminProyectos() {
        JD_AdminstracionProyectos.pack();
        JD_AdminstracionProyectos.setModal(true);
        JD_AdminstracionProyectos.setLocationRelativeTo(this);
        JD_AdminstracionProyectos.setVisible(true);
    }//fin del llamado del JDialog
    
    public void AdminAlumnos() {
        JD_AdministracionAlumnos.pack();
        JD_AdministracionAlumnos.setModal(true);
        JD_AdministracionAlumnos.setLocationRelativeTo(this);
        JD_AdministracionAlumnos.setVisible(true);
    }//fin del llamado del JDialog
    
    public void MenuAdmin() {
        JD_MenuAdmin.pack();
        JD_MenuAdmin.setModal(true);
        JD_MenuAdmin.setLocationRelativeTo(this);
        JD_MenuAdmin.setVisible(true);
    }//fin del llamado del JDialog
    
    public void MenuMaestro() {
        JD_MenuMaestro.pack();
        JD_MenuMaestro.setModal(true);
        JD_MenuMaestro.setLocationRelativeTo(this);
        JD_MenuMaestro.setVisible(true);
    }//fin del llamado del JDialog
    
    public void MenuAlumnos() {
        JD_MenuAlumno.pack();
        JD_MenuAlumno.setModal(true);
        JD_MenuAlumno.setLocationRelativeTo(this);
        JD_MenuAlumno.setVisible(true);
    }//fin del llamado del JDialog
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6P2_VictorCruz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Login;
    private javax.swing.JButton JB_SalirCuentaAdmin;
    private javax.swing.JButton JB_SalirCuentaAlumno;
    private javax.swing.JButton JB_SalirCuentaMaestro;
    private javax.swing.JButton JB_SalirSistema;
    private javax.swing.JButton JB_SalirSistemaAdmin;
    private javax.swing.JDialog JD_AdministracionAlumnos;
    private javax.swing.JDialog JD_AdministracionClases;
    private javax.swing.JDialog JD_AdministracionMaestros;
    private javax.swing.JDialog JD_AdminstracionProyectos;
    private javax.swing.JDialog JD_ClasesAsignadasMaestros;
    private javax.swing.JDialog JD_CrudMaestroProyecto;
    private javax.swing.JDialog JD_ListarModficarAlumnos;
    private javax.swing.JDialog JD_MatriculaAlumnos;
    private javax.swing.JDialog JD_MenuAdmin;
    private javax.swing.JDialog JD_MenuAlumno;
    private javax.swing.JDialog JD_MenuMaestro;
    private javax.swing.JDialog JD_VerInfoProyectos;
    private javax.swing.JMenuItem JMI_CRUDAlumnos;
    private javax.swing.JMenuItem JMI_CRUDClases;
    private javax.swing.JMenuItem JMI_CRUDMaestros;
    private javax.swing.JMenuItem JMI_CRUDProyectos;
    private javax.swing.JMenuItem JMI_ListarModificarAlumnos;
    private javax.swing.JMenuItem JMI_Matricula;
    private javax.swing.JMenuItem JMI_ProyectosMaestro;
    private javax.swing.JMenuItem JMI_VerClasesAsignadas;
    private javax.swing.JMenuItem JMI_VerInfoClaseProyecto;
    private javax.swing.JPasswordField PF_Password;
    private javax.swing.JTextField TF_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
